### ISSUE TITLE
Screenshare working in Zoom  with wayland/sway?

### ISSUE THREAD

**Issue by cyrinux** [synaptiko/.files#6]
Hi @synaptiko,

Thanks for your cool dotfiles, I monitor them time to time.
Do you got screen share with zoom working under sway/wayland?
I got a dark screen when sharing with `gnome-shell-screenshot-dbus-emulator` running.
Any idea? With firefox this works well. This is my solution for the moment.

**Comment by synaptiko** [comment]
Hey @cyrinux,

you're welcome :-) I didn't know anyone is watching my "mess" lol.

The screensharing it tricky and I need to clean-up few old experiments out of my `.files`.

But I'm using native Zoom, it requires three things:
1. running it in X11 mode
2. pretending we are GNOME
3. emulating GNOME screenshot "protocol"

For 1. and 2. I have this: https://github.com/synaptiko/.files/blob/master/sway/Zoom.desktop + https://github.com/synaptiko/.files/blob/master/sway/fix-zoom.sh. It is not ideal as I need to re-run `./sway/fix-zoom.sh` after every update. For 3. I used this as an inspiration: https://gitlab.com/jamedjo/gnome-dbus-emulation-wlr. I didn't like it's written in Ruby as it was somehow heavy (and I don't use Ruby for anything else). So I've written my own simple implementation in Go: https://git.sr.ht/~synaptiko/gnome-shell-screenshot-dbus-emulator. [The binary I have in my `.files`](https://github.com/synaptiko/.files/blob/master/wayland-screen-share/gnome-shell-screenshot-dbus-emulator) is compiled from that repo. The reason why it's not working for you is because I limit it only to my main display, which is `DP-2` (it says `DP-1` because I did change it few time locally and haven't updated it in the repo yet): https://git.sr.ht/~synaptiko/gnome-shell-screenshot-dbus-emulator/tree/master/item/gnome-shell-screenshot-dbus-emulator.go#L23

So if you want to make it work, you need to clone the repo and re-compile the binary with a proper output name. Also you need `grim` installed.

I hope it helps it clarify it for you :-) Let me know if you've succeeded.

**Comment by synaptiko** [comment]
@cyrinux one more thing, I had to also update my Zoom configuration accordingly: https://gitlab.com/jamedjo/gnome-dbus-emulation-wlr/-/issues/1 (check the comment with `showfamewindow=false`).

**Comment by cyrinux** [comment]
Thanks @synaptiko I check all this.
About the desktop file, i think you can store it here and this will just override the default one and no need to do thing after Zoom upgrade: `~/.local/share/applications/Zoom.desktop` .

**Comment by cyrinux** [comment]
With your go binary - you can tweak it to simply pass the screen name as param ? - I well see my desktop in the share screen selector but then I see a black screen. No sure if this is normal or no. I'm alone to test for the moment, so nobody can say me if he see my screen 😸

**Comment by cyrinux** [comment]
Oh I think so its good with this parameters also :-)

https://github.com/QubesOS/qubes-issues/issues/5863#issuecomment-756097248

So thanks you very much, I will try to confirm but no black screen, i think I'm well sharing in the void actually.
What I see also, I'm not able to press the red button in the topbar to stop share. You too?

So can we though to your emulator toy? If I use two monitors, I will be able to select or I will see only the one hardcoded actually?

**Comment by synaptiko** [comment]
@cyrinux thanks for the tip with `~/.local/share/applications/Zoom.desktop`, didn't know I can do it that way :-)

Regarding this comment: https://github.com/QubesOS/qubes-issues/issues/5863#issuecomment-756097248

I think it's related to this https://gitlab.com/jamedjo/gnome-dbus-emulation-wlr/-/issues/1, try to edit your `~/.config/zoomus.conf` to include:
```
[AS]
showframewindow=false
```

Btw. what I'm using to test if my Zoom setup works is just connect to the meeting from the mobile phone, just make sure to mute your microphone otherwise you'll hear a terrible echo loop :-D

> you can tweak it to simply pass the screen name as param ?

Yeah, it could be improved, I just didn't want to mess up with how to figure out which output is available to me etc. Feel free to fork it and adjust as you need :-) I spend too much time making my screen sharing work that I don't want to spend more on it.

> What I see also, I'm not able to press the red button in the topbar to stop share. You too? edit: with moving the zoom bar in bottom its better for me.

What I discovered is that Zoom's control may be "obscured" by other XWayland windows which are on other workspaces. For example if I have VSCode opened and I'll share my screen, I need to switch VSCode to floating mode if I want to be able to control Zoom. I think this may be a bug in either XWayland or wlroots/sway. That was actually a reason why I today updated my `.files` to switch `chromium` to Wayland as I was having a problem with that. Electron 12 was released recently with native Wayland support. You just need to pass the same flags you pass to `chromium`: https://github.com/synaptiko/.files/blob/master/chromium/config. I'm waiting for VSCode to update to it and then this problem with Zoom should be less likely to happen on my setup.

> So can we though to your emulator toy? If I use two monitors, I will be able to select or I will see only the one hardcoded actually?

I wanted to make it work but unfortunately the GNOME protocol is strange, you would need to have monitors "aligned" horizontally in one screenshot. But I couldn't make it work with `grim`. So I basically hard-coded only one of them which also has position { x: 0, y: 0 } and then it works. It's my main monitor so it's not a problem for me.

**Comment by synaptiko** [comment]
Btw. you can also use Zoom's web client from either Firefox or Chrome/Chromium. With pipewire + xdg-desktop-portal it works. I just prefer Zoom's native client, even thought it's doing discreet screenshots in png format which is very slow. When I tried to benchmark it, it was around 1-2 frames per second but it's still acceptable. Screenshots in jpeg are much faster but Zoom cannot use them, I tried to ask support if they would consider to accept that format but no one got back to me so far.

**Comment by cyrinux** [comment]
Thanks a lot for your reply :) Yes I fork it to do minor change to be able to switch screen with a simple systemd unit.
I well change 
```
[AS]
showframewindow=false
```
before getting this black screen, and then after clicking in this advanced mode it was good. I think this add another option but I can't find what is this param for the moment. Weird.

**Comment by cyrinux** [comment]
You can find my fork here.

git.sr.ht:~cyrinux/gnome-shell-screenshot-dbus-emulator

**Comment by cyrinux** [comment]
Present: https://github.com/cyrinux/gnome-shell-screenshot-dbus-emulator/releases/tag/0.1.0
AUR: https://aur.archlinux.org/packages/gnome-shell-screenshot-dbus-emulator

**Comment by synaptiko** [comment]
Wow, amazing, man! :-) Thanks for your effort.
